Encryption
ViktorLitviakov8050/randomNote pull request #5
Opened 2023-08-29 19:59 UTC by ViktorLitviakov8050

Encryption

2023-08-30 10:07 UTC, zasviat approved these changes
good work!

2023-08-30 10:07 UTC, zasviat commented on notes/login/cryptogtapher.py
> +        self.cryptosuit  = Fernet(key)
it's better to rename to 'cryptosuite' or 'crypto_suite'

2023-08-30 10:07 UTC, zasviat commented on notes/login/cryptogtapher.py
> +    def encrypt(self, password) -> str:
![image](https://github.com/ViktorLitviakov8050/randomNote/assets/98279909/7ce12e10-fe13-40c5-b3a1-03bfc4ccab0a)

this method returns bytes not str
Let's change the return value of the 'encrypt' method

2023-08-30 10:07 UTC, zasviat commented on notes/login/views.py
> +from .cryptogtapher import Cryptographer
here's the typo in module name
```suggestion
from .cryptographer import Cryptographer
```

2023-09-04 08:49 UTC, graveetone commented
Bug: InvalidToken Exception when there is request to get random note by token
![image](https://github.com/ViktorLitviakov8050/randomNote/assets/98279909/4aba6615-d6bc-4d52-9854-daf101fa10e6)

Reason: encrypted password was saved in bytes format but as a string
![image](https://github.com/ViktorLitviakov8050/randomNote/assets/98279909/2467c21b-cf49-48e7-ae01-6c17e54228f5)

Fix: Cryptographer now returns decoded (str, not bytes) encrypted password so we save encrypted decoded password to the database

After fix: no exception, password is decoded successfully
![image](https://github.com/ViktorLitviakov8050/randomNote/assets/98279909/848e95c9-4d44-48f8-a260-84fda4ecab29)

2023-09-04 08:52 UTC, graveetone commented
@ViktorLitviakov8050 we need to make a couple of changes in this PR:
1. Let's move cryptographer.py to notes/notes instead of storing it in login module. Cryptographer is used in both 'notes' and 'randomNote' apps.
2. As we have randomNote app in project, we need to specify its name in notes/settings.y to "let the Django know about it"

2023-09-04 08:55 UTC, graveetone requested changes
we need to make a couple of changes in this PR:

1. Let's move cryptographer.py to notes/notes instead of storing it in login module. Cryptographer is used in both 'notes' and 'randomNote' apps.

2. As we have randomNote app in project, we need to specify its name in notes/settings.y to "let the Django know about it"

2023-09-07 15:36 UTC, merged